### ISSUE TITLE
Views' labels are not visible because of bootstrap css styles

### ISSUE THREAD

**Issue by simone960** [backdrop-contrib/views_bootstrap#4]
I find that the Bootstrap css file is loaded inside the Views where it affect the style of the Views and can't see the labels. Any idea ?

![bootstrap views](https://user-images.githubusercontent.com/7530286/32580766-fce99d42-c53a-11e7-8cd7-8c8ca0b1b0cc.png)

**Comment by simone960** [comment]
I think not only that, the bootstrap js file also loaded and affected the Admin theme. I can't move a menu item to place it under the parent menu. Go to Menu > Primary navigation. You can't do things like drag the "About Us" to place it under "Home".

Home
- About Us

**Comment by simone960** [comment]
Ok, just noticed there's a configuration where Bootstrap styles (css) and scripts (js) can be excluded:

Go to: Configuration > User Interface > Administer Views Bootstrap settings

Here what I configured:
Select: **All pages except those listed**

Specify pages to be excluded by paths, e.g:
admin/*
node/add/*
node/*/edit

**Comment by bugfolder** [comment]
Just adding an explanatory note here after some discussion that starts at https://github.com/backdrop-contrib/views_bootstrap/issues/27#issuecomment-1181841605. The vanishing labels happens because Bootstrap adds CSS for selector `.label`, which is applied on the Views admin page if "Preview" is checked (because then the BS libraries are loaded). So there is now a CSS shim, `views_bootstrap.css`, that contains some CSS that restores the labels to visibility (though not precisely what they were before).
