### ISSUE TITLE
Tabs not showing correct text/label

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/views_bootstrap#5]
I'm trying to use the Views Bootstrap module to show my results in tabs. 

I am trying to use a text field as the label for the each tab, the text field I want to use is a select list. My selection is not showing up as I would expect in the tab. Instead, I'm seeing the word "array" in each tab (see image). 

We tested another field that was not a select list to see if this problem was only for select lists. But, it did not work with a simple text field either. 

![fourth_street_housing_co-op___riverton](https://user-images.githubusercontent.com/3144571/43360889-8c5e3320-9286-11e8-8ad1-bf31d4732251.png)

**Comment by stpaultim** [comment]
Note: My colleague is currently working on a pull request to fix this. We currently have a fix that works for us, but we would like to make our fix work better for more common use cases.

**Comment by Radcliffe** [comment]
In our case, the tab label as received by the template is an array instead of a string. It looks like this:

`$tab == array(array('value' => 'ST'))`

My pull request replaces the value of `$tab`with `$tab[0]['value']` in the case that `$tab` is an array.
This solves our immediate problem. But I don't know why the template is receiving the wrong value, and I'm not sure that the template is the right place to fix the problem.

Also, we would prefer the tab label to match the label for the selected item, not the key. For example, our room field has the following allowed values.

    ST|Studio
    1B|1 Bedroom
    2B|2 Bedroom
    3B|3 Bedroom
    4B|4 Bedroom
    5B|5 Bedroom

After my fix, the tab labels are ST, 1B, 2B, etc. But they should be Studio, 1 Bedroom, 2 Bedroom, etc. How can we achieve this?

We are running Backdrop version 1.10.0 with Views Bootstrap v1.1.0 and PHP v5.5.9.

**Comment by Radcliffe** [comment]
Fixed.
